<?php

namespace AppBundle\Repository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends \Doctrine\ORM\EntityRepository
{
    public function findWithCompany($id)
    {
        $dql = "SELECT c, s 
                FROM AppBundle\Entity\Contact c 
                LEFT JOIN c.societe s
                WHERE c.id = :id";

        $query = $this->getEntityManager()->createQuery($dql);

        $result = $query->setParameter('id', $id);

        return $result->getSingleResult();
    }
}
